=== bushrayasmin24/techment-training2020/day15/studentsstructure.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT students (student+)>
<!ELEMENT student (rollno,name,dept) >
<!ELEMENT rollno (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT dept (#PCDATA) >

=== bushrayasmin24/techment-training2020/day15/students.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE students SYSTEM "studentsstructure.dtd">
<students>
	
	<student>
		<rollno>1001</rollno>
		<name>Yasmin</name>
		<dept>CIVIL</dept>
	</student>
	
	<student>
		<rollno>1002</rollno>
		<name>Aaliya</name>
		<dept>Electrical</dept>
	</student>
</students>
